pub const CHUNK_SIZE: i32 = 16;
pub const SPAWN_DISTRICTS_RETRIES: i32 = 10;
pub const SPAWN_DISTRICTS_MIN_DISTANCE : i32 = 5;
pub const NUM_RECENTER : i32 = 2;
pub const TARGET_DISTRICT_AMOUNT : u32 = 16; 
pub const OFF_LIMITS_ROUGHNESS : f32 = 6.0;
pub const OFF_LIMITS_GRADIENT : f32 = 1.0;
pub const URBAN_WATER_LIMIT: f32 = 0.33; // Maximum water percentage for urban districts
pub const URBAN_SIZE_MIN: u32 = 3; // Minimum number of urban superdistricts (city floor)
pub const URBAN_SIZE_MAX: u32 = 5; // Maximum number of urban superdistricts (city cap)
pub const URBAN_GROWTH_CUTOFF: f32 = 0.10; // Candidate score needed to grow the city up to URBAN_SIZE_MIN
pub const URBAN_GROWTH_CUTOFF_HIGH: f32 = 0.33; // Higher candidate score needed to grow beyond the minimum, up to URBAN_SIZE_MAX
pub const URBAN_OPTION_SCORE_MAX: f32 = 0.75; // Max superdistrict_score to be eligible as an urban (prime) candidate
pub const RURAL_OPTION_SCORE_MAX: f32 = 1.5; // Max superdistrict_score to be classified Rural (above this is Off-Limits)
pub const ADJACENCY_WEIGHT: f32 = 3.0; // Weight for adjacency in district comparison scoring
pub const URBAN_RELATIVE_TO_PRIME: f32 = 0.0; // score needed exceed to be under to be urban in relation to prime district