mod parcel;
mod district;
mod test;
mod adjacency;
mod analysis;
mod merge;
mod constants;
mod data;
mod classification;
mod wall;
mod footprint;
mod parcel_painter;
mod gate;
mod paint_palette;
pub mod subdivide;

pub use parcel::Parcel;
pub use parcel::ParcelID;
pub use analysis::ParcelAnalysis;
pub use parcel::ParcelType;
pub use parcel::generate_parcels;
pub use district::District;
pub use district::DistrictID;
pub use data::{ParcelData, HasParcelData};
pub use parcel_painter::*;
pub use wall::{build_wall, get_wall_points, WallType};
pub use footprint::{regularize_urban_footprint, reconcile_districts_to_footprint};
pub use gate::build_wall_gate;
pub use paint_palette::{PaintPaletteId, PaintPalette, PaintPalettesFile};
